version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: .
    container_name: fastapi-app
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
